[package]
name = "neones"
version = "0.1.0"
authors = ["Muhamamd Sohail <mhsohail56@gmail.com>"]
license = "MIT"
repository = "https://github.com/msohaill/neones"
readme = "README.md"
edition = "2021"

[dependencies]
sdl2 = "^0.35.2"
